services:
  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  db:
    image: postgres:17-alpine
    container_name: url-shortener-db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "minhasenhae?08"
      POSTGRES_DB: "short_url_db"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: