name: CI - Lint & Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do código
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: ✅ Executar Lint
        run: npm run lint

      - name: 🧪 Executar Testes
        run: npm run test -- --ci --coverage

      - name: 💾 Salvar cobertura de testes
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
